/*
1. Crie um banco de dados para um e-commerce, onde o sistema
trabalhará com as informações dos produtos deste e-commerce.  
*/

CREATE DATABASE DB_ECOMMERCE_POP;

/*
2. Crie uma tabela de produtos e determine 5 atributos relevantes
dos produtos para se trabalhar com o serviço deste e-commerce.
*/

USE DB_ECOMMERCE_POP;

CREATE TABLE TB_LPS(
ID BIGINT AUTO_INCREMENT NOT NULL,
ARTISTA CHAR (60),
ALBUM CHAR (100),
ANO_DE_LANCAMENTO INT,
GENERO CHAR (50),
VALOR DECIMAL,
PRIMARY KEY (ID)
);

/*
3. Insira nesta tabela no mínimo 8 dados (registros).
*/

INSERT INTO TB_LPS (ARTISTA, ALBUM, ANO_DE_LANCAMENTO, GENERO, VALOR) VALUES ('BRITNEY SPEARS','BLACKOUT','2007','ELECTROPOP','399.99');
INSERT INTO TB_LPS (ARTISTA, ALBUM, ANO_DE_LANCAMENTO, GENERO, VALOR) VALUES ('LADY GAGA','THE FAME','2008','ELECTROPOP','359.99');
INSERT INTO TB_LPS (ARTISTA, ALBUM, ANO_DE_LANCAMENTO, GENERO, VALOR) VALUES ('JANET JACKSON','DISCIPLINE','2008','POP/R&B','429.99');
INSERT INTO TB_LPS (ARTISTA, ALBUM, ANO_DE_LANCAMENTO, GENERO, VALOR) VALUES ('MNEK','LANGUAGE','2018','POP/R&B','299.99');
INSERT INTO TB_LPS (ARTISTA, ALBUM, ANO_DE_LANCAMENTO, GENERO, VALOR) VALUES ('RIHANNA','ANTI','2016','POP/ALTERNATIVE R&B','399.99');
INSERT INTO TB_LPS (ARTISTA, ALBUM, ANO_DE_LANCAMENTO, GENERO, VALOR) VALUES ('TONI BRAXTON','TONI BRAXTON','1993','POP/R&B','599.99');
INSERT INTO TB_LPS (ARTISTA, ALBUM, ANO_DE_LANCAMENTO, GENERO, VALOR) VALUES ('MADONNA','EROTICA','1992','POP/DANCE','619.99');
INSERT INTO TB_LPS (ARTISTA, ALBUM, ANO_DE_LANCAMENTO, GENERO, VALOR) VALUES ('WHITNEY HOUSTON','IM YOUR BABY TONIGHT','1990','POP/R&B','599.99');

/*
4. Faça um SELECT que retorne todes os produtos com o valor maior do que 500.
*/

SELECT * FROM TB_LPS WHERE VALOR > '500.00';

/*
5. Faça um SELECT que retorne todes os produtos com o valor menor do que 500.
*/

SELECT * FROM TB_LPS WHERE VALOR < '500.00';

/*
6. Ao término, atualize um registro desta tabela através de uma query de atualização.
*/

UPDATE TB_LPS SET VALOR = "409.99" WHERE  ID = 3;
SELECT * FROM TB_LPS;